version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inmeta-api-prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: inmeta
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: inmeta-db-prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inmeta
    ports:
      - "5432:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

volumes:
  pgdata_prod:
